<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1dTM1Mx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1dTM1Mx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1dTM1Mx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1dTM1Mx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1dTM1Mx\App_KernelDevDebugContainer([
    'container.build_hash' => '1dTM1Mx',
    'container.build_id' => 'f3392362',
    'container.build_time' => 1634308262,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1dTM1Mx');
